# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                               #
#  FFFFFFFFFFFFFFFFFFFFFF LLLLLLLLLLL            EEEEEEEEEEEEEEEEEEEEEE XXXXXXX        XXXXXXX  #
#  F::::::::::::::::::::F L:::::::::L            E::::::::::::::::::::E X:::::X        X:::::X  #
#  FF::::::FFFFFFFFF::::F LL:::::::LL            EE::::::EEEEEEEE:::::E X:::::X        X:::::X  #
#    F:::::F       FFFFFF   L:::::L                E:::::E       EEEEEE XXX::::X      X::::XXX  #
#    F:::::F                L:::::L                E:::::E                X::::::X  X::::::X    #
#    F::::::FFFFFFFFFF      L:::::L                E::::::EEEEEEEEEE        X:::::XX:::::X      #
#    F:::::::::::::::F      L:::::L                E:::::::::::::::E          X::::::::X        #
#    F::::::FFFFFFFFFF      L:::::L                E::::::EEEEEEEEEE        X:::::XX:::::X      #
#    F:::::F                L:::::L                E:::::E                X::::::X  X::::::X    #
#    F:::::F                L:::::L       LLLLLL   E:::::E       EEEEEE XXX::::X      X::::XXX  #
#  FF:::::::FF            LL::::::LLLLLLLL:::::L EE::::::EEEEEEEE:::::E X:::::X        X:::::X  #
#  F:::::::::F            L::::::::::::::::::::L E::::::::::::::::::::E X:::::X        X:::::X  #
#  FFFFFFFFFFF            LLLLLLLLLLLLLLLLLLLLLL EEEEEEEEEEEEEEEEEEEEEE XXXXXXX        XXXXXXX  #
#                                                                                               #
#  FleX/Bukkit Engine by Team Luminous Development.                                             #
#  Fukkit: v2.56.3b-SNAPSHOT                                                                    #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Leave this unchanged unless you know what you're doing.
config-version: 2

# flow-line enforcement anti-cheat.
flow-line-enforcement:

  # New types of cheat-proof algorithms are implemented all the time.
  enabled: false
  
  # Enable the replay/overwatch system.
  # Allow players to watch reported players and determine a verdict.
  # The algorithm for this is extremely extensive and can affect performance.
  # Flow-line-Enforcement must be enabled for this to take effect.
  overwatch: false
  
combat:

  # Delay between player hit damage in ticks.
  # The Minecraft default 20 ticks.
  hit-registration: 19
  
chat:
  
  # Global chat filter.
  filter:
    
    # Enable/Disable the global chat filter.
    enabled: true
    
    # Plural forms of all words in the filter are blocked.
    # This also means all "y" endings are replaced with "ies".
    # See examples of this below.
    censor:
    - nigger # This censors nigger"s" as well.
    - trann # This censors trann"y" and trann"ies" as well, etc.
    - fag
    - faggot
    - fagget
  
  # Global chat delay.
  # Staff members are not affected.
  delay:
  
    # Simple anti-spam system.
    # Enable/Dsiable player chat delay.
    enabled: true
    
    # Chat delay in seconds.
    # FleX default: 1.5
    seconds: 1.5
    
    # The rank weight at which a player can bypass the chat delay.
    # FleX default: 10
    bypass-weight: 10
    
  mentions:
  
    # Player chat mentions.
    # Enable/Dsiable player mentions using @(player).
    # Mentioning players pings them and highlights their name.
    enabled: true
