# Theme players will start to see by default.
# If no themes are present, all default themes will be generated again.
# If no default is specified then a gui will open on first join, telling the player to select a theme.
# This can also be used as an anti-spam/anti-bot stratergy as it requires theme selection before anything else.
default: 'Default'

# Enable/Disable theme selection.
# The theme in the "Default" setting will always be used regardless of this setting.
theme-selection-enabled: true

# This is unicode you can use in themes, with enclosed bracketing. []
# Example: [HEART] would show ❤ in-game.
unicode:

  HEART: '❤'
  HIGH_VOLTAGE: '⚡'
  BLACK_PARALLEOGRAM: '▰'
  WHITE_PARALLEOGRAM: '▱'
  DOUBLE_ARROW_POINTING_LEFT: '«'
  DOUBLE_ARROW_POINTING_RIGHT: '»'